export const data = [
  {
    id: "asdklaskd",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/300px-Flag_of_Chile.svg.png",
    country: "chile",
    population: "12321321",
    region: "america",
    capital: "santiago",
  },
  {
    id: "asdklaskda",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/300px-Flag_of_Chile.svg.png",
    country: "chile",
    population: "12321321",
    region: "america",
    capital: "santiago",
  },
  {
    id: "asdklaskd",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/300px-Flag_of_Chile.svg.png",
    country: "chile",
    population: "12321321",
    region: "america",
    capital: "santiago",
  },
  {
    id: "asdklaskd",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/300px-Flag_of_Chile.svg.png",
    country: "chile",
    population: "12321321",
    region: "america",
    capital: "santiago",
  },
  {
    id: "asdklaskd",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/300px-Flag_of_Chile.svg.png",
    country: "chile",
    population: "12321321",
    region: "america",
    capital: "santiago",
  },
  {
    id: "asdklaskd",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/300px-Flag_of_Chile.svg.png",
    country: "chile",
    population: "12321321",
    region: "america",
    capital: "santiago",
  },
  {
    id: "asdklaskd",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/300px-Flag_of_Chile.svg.png",
    country: "chile",
    population: "12321321",
    region: "america",
    capital: "santiago",
  },
  {
    id: "asdklaskd",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/300px-Flag_of_Chile.svg.png",
    country: "chile",
    population: "12321321",
    region: "america",
    capital: "santiago",
  },
];
